name: Deploy IIUC Service Portal
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 6251
          timeout: 2m
          command_timeout: 30m
          request_pty: true
          script: |
            export PATH=$PATH:/root/.nvm/versions/node/v18.20.4/bin:/usr/local/bin:/usr/bin:/bin
            cd /var/www/iiuc-service-portal || exit 1
            echo "➡️ Pulling latest code..."
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            echo "➡️ Installing dependencies..."
            bun install
            echo "➡️ Building application..."
            bun run build
            echo "➡️ Restarting pm2..."
            pm2 restart 0
